name: my-app
env:
  NODE_ENV: production

build:
  frontend:
    command: npm run build:client
  backend:
    command: npm run build:server
  # install: true
start:
  web: node server/index.js

services:
  web:
    port: 3000
    command: npm run dev
    env:
      NODE_ENV: production
    routes:
      - path: /
        destination: web
  db:
    image: postgres
